"""
My GMP Backend — GRAFOMEM adapter template.

Scaffold generated by `grafomem init`. Implements the MemoryBackend Protocol
with a minimal in-memory store. Customize this to wrap your own memory system.

Run `grafomem check -b my_backend:MyBackend` to validate Protocol compliance.
Run `grafomem conformance -b my_backend:MyBackend` for the full conformance suite.
"""

from __future__ import annotations

from collections.abc import Iterator
from datetime import datetime, timezone

from aml.backends.interface import (
    Capability,
    CapabilityNotSupported,
    Memory,
    RetrieveOptions,
    WriteOptions,
)


class MyBackend:
    """Minimal GMP-conformant backend. Starts with AUDIT only.

    To claim additional capabilities:
    1. Add the flag to capabilities()
    2. Implement the corresponding behavior
    3. Run `grafomem conformance` to verify

    See docs/adapter-guide.md for the full walkthrough.
    """

    __grafomem_interface__ = "0.2.0"
    __grafomem_adapter_metadata__ = {
        "underlying_system": "my-system",  # TODO: your system name
        "notes": "Scaffold adapter — customize me",
    }

    def __init__(self) -> None:
        self._store: dict[int, Memory] = {}
        self._next = 0

    # -- Capabilities -------------------------------------------------------
    # Start with AUDIT. Add flags as you implement them:
    #   Capability.SUPERSESSION_CHAIN  → implement supersede()
    #   Capability.BI_TEMPORAL         → honor as_of in retrieve()
    #   Capability.HARD_DELETE         → implement delete()
    #   Capability.MULTI_TENANT       → honor tenant_id in write/retrieve
    #   Capability.PROVENANCE         → attach source metadata
    #   Capability.CRYPTOGRAPHIC_PROVENANCE → sign with Ed25519

    def capabilities(self) -> set[Capability]:
        return {Capability.AUDIT}

    # -- Core operations ----------------------------------------------------

    def write(self, content: str, options: WriteOptions) -> int:
        """Store content and return an opaque reference."""
        # TODO: Wire this to your storage backend
        if options.tenant_id is not None:
            raise CapabilityNotSupported(Capability.MULTI_TENANT, "write")

        ref = self._next
        self._next += 1
        self._store[ref] = Memory(
            ref=ref,
            content=content,
            written_at=datetime.now(tz=timezone.utc),
        )
        return ref

    def retrieve(self, query: str, options: RetrieveOptions) -> list[Memory]:
        """Return memories matching the query within budget_tokens."""
        # TODO: Replace with semantic/vector retrieval
        if options.as_of is not None:
            raise CapabilityNotSupported(Capability.BI_TEMPORAL, "retrieve")
        if options.tenant_id is not None:
            raise CapabilityNotSupported(Capability.MULTI_TENANT, "retrieve")

        budget = options.budget_tokens or 9999
        out, used = [], 0
        # Simple substring match — replace with your retrieval logic
        for ref, mem in self._store.items():
            if query.lower() in mem.content.lower():
                cost = len(mem.content)
                if used + cost > budget:
                    break
                out.append(mem)
                used += cost
        return out

    def delete(self, ref: int) -> bool:
        """Delete a memory by reference. Requires HARD_DELETE capability."""
        raise CapabilityNotSupported(Capability.HARD_DELETE, "delete")

    def supersede(self, old_ref: int, content: str, options: WriteOptions) -> int:
        """Replace a memory with updated content. Requires SUPERSESSION_CHAIN."""
        raise CapabilityNotSupported(Capability.SUPERSESSION_CHAIN, "supersede")

    def audit(self) -> Iterator[Memory]:
        """Yield all stored memories for compliance auditing."""
        return iter(list(self._store.values()))

    def flush(self) -> None:
        """Ensure all writes are visible to subsequent retrieves."""
        pass  # In-memory store is always consistent
